config/routes.rb
PayaloguePlusApiExample::Application.routes.draw do
  root :to => "home#index"
  match "report" => "purchases#report"
  resources :products, :only => :index do
    resources :purchases, :only => [:new, :create]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :purchases
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :product

  def update_status_by_valid_request(params)
    return if !payment_id_equals?(params[:payment_id]) || !price_setting_id_equals?(params[:price_setting_id]) || !status_equals?(params[:status])
    update_attributes(:status => params[:status])
  end

  private
  def payment_id_equals?(params_payment_id)
    zaypay_payment_id == params_payment_id.to_i
  end
  
  def price_setting_id_equals?(params_price_setting_id)
    product.price_setting_id == params_price_setting_id.to_i
  end
  
  def status_equals?(params_status)
    @ps = Zaypay::PriceSetting.new(product.price_setting_id)
    @zaypay_payment = @ps.show_payment(zaypay_payment_id)
    @zaypay_payment[:payment][:status] == params_status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_filter :assign_parent_product, :only => [:new , :create]
  before_filter :bust_response_headers, :only => :new

  def new
    respond_to do |format|
      format.html{
        if country = @ps.ip_country_is_configured?(request.remote_ip)
          @ps.locale = Zaypay::Util.stringify_locale_hash(country[:locale])
        end
      }
      format.js{
        if params[:country].present? && params[:language].present?
          @ps.locale = params[:language] + "-" + params[:country]
        end
      }
    end
  end

  def create
    # set locale first before calling #list_payment_methods
    # locale and payment_method_id must be set before calling create_payment
    
    if params[:language].blank? || params[:country].blank? || params[:payment_method].blank?
      flash[:error] = ''
      flash[:error] << "You did not select a language.<br/>" if params[:language].blank?
      flash[:error] << "You did not select a country.<br/>"   if params[:country].blank?
      flash[:error] << "You did not select a payment method." if params[:payment_method].blank?
      redirect_to new_product_purchase_path(@product) and return
    end
    
    @ps.locale = params[:language] + "-" + params[:country]
    @ps.payment_method_id = params[:payment_method]
    @purchase = @product.purchases.create!
    begin
      @zaypay_payment = @ps.create_payment(:payalogue_id => @product.payalogue_id, :purchase_id => @purchase.id)
    rescue => e
      if e.type == :locale_not_set
        flash[:error] = "There was an error with the country or language you provided"
      elsif e.type == :payment_method_id_not_set
        flash[:error] = "There was an error with the payment method you provided"
      else
        flash[:error] = "Oops... Something went wrong, please try again"
      end
      @purchase.destroy
      redirect_to new_product_purchase_path(@product)
    else
      @purchase.update_attributes(:zaypay_payment_id => @zaypay_payment[:payment][:id])
      redirect_to "https://secure.zaypay.com#{@zaypay_payment[:payment][:payalogue_url]}"
    end
  end

  def report
    if params[:payment_id].present? && params[:price_setting_id].present? && params[:purchase_id].present? && params[:status].present?
      @purchase = Purchase.find(params[:purchase_id])
      @purchase.update_status_by_valid_request(params) if @purchase
    end
    render :layout => false, :text => "*ok*"
  end

  private ################################################################
  def assign_parent_product
    @product = Product.find(params[:product_id])
    @ps = Zaypay::PriceSetting.new(@product.price_setting_id)
  end
  
  def bust_response_headers
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/home/index.html.haml
%h2
  Welcome!

%p
  This is an example on how to implement the ZayPay API on a Ruby on Rails site
= link_to 'Check out our super awesome products' , products_path, :id => 'products_index_button', :class => "btn btn-primary btn-large"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payalogue + Api Example</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body onunload="">
    <div id="container">
      <div id="table_unit">
        <% if flash[:error] %>
          <div class="alert alert-error">
            <%= flash[:error].html_safe %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/products/_product.html.haml
%tr{:id => "product_#{product.id}" }
  %td.product_name
    = link_to product.name, new_product_purchase_path(product)
  %td.product_description
    = product.description

app/views/products/index.html.haml
%table#our_products.table.table-striped
  %thead
    %tr
      %th 
        name
      %th 
        description
  %tbody
    = render @products

app/views/purchases/_generate_select_menu.html.haml
- if @ps.locale
  #payment_method_selection.row_wrapper
    .label_wrap
      = label_tag :payment_method, "Select your preferred payment method", :class => 'control-label'
    .input_wrap
      - @ps.list_payment_methods.each do |method|
        #button_row
          = radio_button_tag :payment_method, method[:payment_method_id]
          = label_tag "payment_method_#{method[:payment_method_id]}", method[:very_short_instructions_with_amount]

  #submit_wrapper
    .label_wrap
    .input_wrap
      = submit_tag "Proceed to payment screen", :class => 'btn btn-primary submit_button'

app/views/purchases/new.html.haml
= form_tag product_purchases_path(@product), { :class => "form-horizontal", :id => "purchase_form", :autocomplete => :off } do |f|
  %div#language_selection.row_wrapper
    .label_wrap
      = label_tag :language, 'Select your language', :class => 'control-label'
    .input_wrap
      = select_tag :language, options_for_select( @ps.list_languages.map{ |language| [ language[:native_name], language[:code] ]}, @ps.locale_for_ip(request.remote_ip)[:language])

  %div#country_selection.row_wrapper
    .label_wrap
      = label_tag :country, "Select your country", :class => 'control-label'
    .input_wrap
      = select_tag :country, options_for_select( @ps.list_countries.map{ |country|  [ country[:name], country[:code] ]}, @ps.locale_for_ip(request.remote_ip)[:country]), :include_blank => true

  %div#payment_method_and_submit
    = render :partial => 'generate_select_menu'

app/views/purchases/new.js.erb
$('#payment_method_and_submit').html("<%= escape_javascript render 'generate_select_menu' %>");